### ISSUE TITLE
TurnCounterComponentの実装

### ISSUE THREAD

**Issue by s-haya-123** [f-naoto832/ploutos#16]

**Comment by hahnah** [comment]
branch: [feature/#16-create-turn-counter-component](https://github.com/f-naoto832/ploutos/tree/feature/%2316-create-turn-counter-component)

**Comment by hahnah** [comment]
pr: [https://github.com/f-naoto832/ploutos/pull/20](https://github.com/f-naoto832/ploutos/pull/20)
